// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn98Z0MwU-VCujoCA6BUAshcpgS8xlqK0',
    appId: '1:577919622150:web:3a66680c338ef80dceb787',
    messagingSenderId: '577919622150',
    projectId: 'dyslexiaapp-1',
    authDomain: 'dyslexiaapp-1.firebaseapp.com',
    storageBucket: 'dyslexiaapp-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNjcjACyKuWpWYxu6b1N1L-0UoO3dF3YU',
    appId: '1:577919622150:android:796260c90d5402c7ceb787',
    messagingSenderId: '577919622150',
    projectId: 'dyslexiaapp-1',
    storageBucket: 'dyslexiaapp-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYMsOmTzxVhW_5Wk8k66G0LG7ZJR71alg',
    appId: '1:577919622150:ios:80731c7d2394343dceb787',
    messagingSenderId: '577919622150',
    projectId: 'dyslexiaapp-1',
    storageBucket: 'dyslexiaapp-1.firebasestorage.app',
    androidClientId: '577919622150-9an94ubmin17c2tqh2tj54lg4c72ite3.apps.googleusercontent.com',
    iosClientId: '577919622150-b1bf2iflrdui992r9u274i34e6m6195p.apps.googleusercontent.com',
    iosBundleId: 'com.example.desco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYMsOmTzxVhW_5Wk8k66G0LG7ZJR71alg',
    appId: '1:577919622150:ios:80731c7d2394343dceb787',
    messagingSenderId: '577919622150',
    projectId: 'dyslexiaapp-1',
    storageBucket: 'dyslexiaapp-1.firebasestorage.app',
    androidClientId: '577919622150-9an94ubmin17c2tqh2tj54lg4c72ite3.apps.googleusercontent.com',
    iosClientId: '577919622150-b1bf2iflrdui992r9u274i34e6m6195p.apps.googleusercontent.com',
    iosBundleId: 'com.example.desco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn98Z0MwU-VCujoCA6BUAshcpgS8xlqK0',
    appId: '1:577919622150:web:5dabee737db8b31aceb787',
    messagingSenderId: '577919622150',
    projectId: 'dyslexiaapp-1',
    authDomain: 'dyslexiaapp-1.firebaseapp.com',
    storageBucket: 'dyslexiaapp-1.firebasestorage.app',
  );
}
